### ISSUE TITLE
How to change "/comments/" to "/reviews"/

### ISSUE THREAD

**Issue by nafeeees** [stormuk/wp-comments-page#1]
Hi,

I want to  change "/comments/" to "/reviews"/
how can I change it? Please let me know.

Example: colon-products-review/acai-berry-blast.html/reviews

Thank You

**Comment by barrywoolgar** [comment]
Hello. This code is not something we support anymore so I cannot give you much help here. I also don't know if it will work with more recent WordPress builds. However, if you've got it working as-is, you just want to modify these two functions to replace `comments` with `reviews`:

https://github.com/stormuk/wp-comments-page/blob/master/storm-comments-page.php

- comments_endpoint_query_vars($vars)
- comments_endpoint_get_comment_link($url)

No need to rename the functions themselves, as you'll just make more work for yourself.

You may also need to replace instances of `$wp_query->query['comments']` with `$wp_query->query['reviews']`, but I'm not certain about that.

**Comment by nafeeees** [comment]
Thanks for the reply.

Not working 404 pages open.

You have any solution. I want to open my comments section to the next page or pagination and change the slug permalink/reviews and change the meta title and description.

**Comment by barrywoolgar** [comment]
I'm sorry, I can't provide any further help with this as I don't have the code installed anywhere. You should be able to write out some debug statements to help you understand where the code is deviating from what you expect to happen.

**Comment by nafeeees** [comment]
Thank You  barrywoolgar

**Comment by nafeeees** [comment]
Hi,

Can you develop a plugin for me and how many charges for the plugin?

**Comment by barrywoolgar** [comment]
Hello, sorry we're not able to do that at present. If you find a freelancer then they could fork this repo and make the changes for you to use, though I do wonder if this code is bit too old now for modern WordPress best practices. Good luck
